import = [
  "~/.config/alacritty/themes/themes/coolnight.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
dimensions.columns = 160
dimensions.lines = 80

decorations = "Buttonless"

opacity = 0.7
blur = true

option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font Mono"
size = 18

[keyboard]
bindings = [
 { key = "Return", mods = "Alt", action = "ToggleFullscreen" },
]

